[workspace]
members = ["microchassis", "microchassis-build", "exampleservice"]

# exampleservice binary test
[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
debug = 1
strip = false
