[advisories]
db-path = "~/.cargo/advisory-db"
db-urls = ["https://github.com/rustsec/advisory-db"]
vulnerability = "deny"
unmaintained = "warn"
yanked = "warn"
notice = "warn"
ignore = [
  #"RUSTSEC-0000-0000",
]

[licenses]
unlicensed = "deny"
allow = ["MIT", "Apache-2.0", "BSD-3-Clause"]
deny = []
copyleft = "deny"
allow-osi-fsf-free = "neither"
default = "deny"
confidence-threshold = 0.95
exceptions = [
  # https://spdx.org/licenses/Unicode-DFS-2016.html
  { allow = ["Unicode-DFS-2016"], name = "unicode-ident", version = "*" },
]

[licenses.private]
ignore = false

[bans]
multiple-versions = "warn"
wildcards = "deny"
highlight = "all"
allow = [
  #{ name = "name", version = "*" },
]
deny = [
  # Nothing wrong with slog. Let's just not mix logging libs.
  { name = "slog", version = "*" },
  # Let's try to do everything with rustls.
  { name = "openssl", version = "*" },
]
