include = ["**/*.toml"]

[formatting]
column_width = 10000
allowed_blank_lines = 1
reorder_keys = false
reorder_arrays = false
array_auto_expand = false
array_auto_collapse = true

[[rule]]
include = ["Cargo.toml", "**/Cargo.toml"]
keys = ["dependencies", "*-dependencies", "features"]

[rule.formatting]
reorder_keys = true
reorder_arrays = true
