[package]
name = "microchassis"
description = "[WIP] Chassis for Rust Microservices"
version = "0.1.0"
edition = "2021"
authors = ["Folke Behrens <folke@gmail.com>"]
repository = "https://github.com/cloneable/microchassis"
license = "Apache-2.0"
exclude = [".gitignore", ".github", "target"]

[dependencies]
futures = "0.3"
log = "0.4"
thiserror = "1"
tokio = { version = "1", features = [
    "macros",
    "rt-multi-thread",
    "signal",
    "sync",
    "time",
    "tracing",         # console subscriber
] }

console-subscriber = { version = "0.1", optional = true }
tracing = { version = "0.1", features = [
    "log",
    "max_level_trace",
    "release_max_level_info",
], optional = true }
tracing-log = { version = "0.1", optional = true }
tracing-subscriber = { version = "0.3", features = [
    "json",
    "registry",
    "tracing-log",
], optional = true }

[features]
default = ["service", "std"]
service = ["tracing"]
cli = []
std = []
tracing = [
    "dep:console-subscriber",
    "dep:tracing",
    "dep:tracing-log",
    "dep:tracing-subscriber",
]
