[package]
name = "exampleservice"
version = "0.0.0"
edition = "2021"

[dependencies]
anyhow = "1"
microchassis = { path = ".." }
prost = "0.11"
tokio = { version = "1", features = ["full"] }
tonic = "0.8"
tonic-health = "0.7"
tonic-reflection = "0.5"

[build-dependencies]
tonic-build = "0.8"
